```{r}
library(dplyr)
library(ggplot2)
winplot <- function(combo){
  x <- c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
  p <- c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
  n <- c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
  s <- c("0.0-0.1","0.1-0.2","0.2-0.3","0.3-0.4","0.4-0.5","0.5-0.6","0.6-0.7","0.7-0.8","0.8-0.9","0.9-1.0")
  h <- data.frame(x,p,n,s)
  for(i in c(1:10)){
    h$x[i] <- .1*i-.05
    temp <- filter(combo, Tpct > .1*(i-1), Tpct < .1*i)
    h$p[i] <- nrow(filter(temp, Win == 1)) / nrow(temp)
    h$n[i] <- nrow(temp)
  }
  ggplot(h, aes(x=x, y=p, color="red")) +
    geom_point(aes(size=n)) +
    geom_text(aes(label=s,hjust=0, vjust=2)) +
    geom_abline(intercept = 0, slope = 1) +
    xlim(0, 1) +
    ylim(0, 1) +
    ggtitle("Predicted Home Win Probability Validation") +
    xlab("Predicted Home Win Percentage") +
    ylab("Actual Home Win Percentage")
}

count <- 1
```

1st round
```{r}
a <- read.csv("./Data-1st-rd.csv", header = TRUE)

a$Top <- as.character(a$Top)
a$Bottom <- as.character(a$Bottom)
a$T1 <- as.numeric(aaa$Tseed == 1)
a$T2 <- as.numeric(aaa$Tseed == 2)
a$T3 <- as.numeric(aaa$Tseed == 3)
a$T4 <- as.numeric(aaa$Tseed == 4)
a$T5 <- as.numeric(aaa$Tseed == 5)
a$T6 <- as.numeric(aaa$Tseed == 6)
a$T7 <- as.numeric(aaa$Tseed == 7)
a$T8 <- as.numeric(aaa$Tseed == 8)
a$ML <- 0
a$WinSeed <- 0
a$Winner <- ""
a$LoseSeed <- 0
a$Loser <- ""
a$Winpct <- 0

aa <- a[c(1:192),]

w4 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Toff+Boff+Tdef+Bdef+Tsos+Bsos
         +Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+This+Bhis+T1+T2+T3+T4+T5+T6+T7+T8,data=aa)
a$result <- suppressWarnings(predict(w4, a))
sd1 <- sd(resid(w4))
a$Tpct <- pt((a$result-.5)/(sd1), nrow(a))
a$Bpct <-  pt(-(a$result-.5)/(sd1), nrow(a))
#winplot(a[c(1:192),])

for(i in c(1:224)){
  if(a$result[i] > .5){
    a$WinSeed[i] <- a$Tseed[i]
    a$Winner[i] <- as.character(a$Top[i])
    a$LoseSeed[i] <- a$Bseed[i]
    a$Loser[i] <- as.character(a$Bottom[i])
    a$ML[i] <- a$Tpct[i]/a$Bpct[i]*-100
    a$Winpct[i] <- a$Tpct[i]
  }
  if(a$result[i] < .5){
    a$WinSeed[i] <- a$Bseed[i]
    a$Winner[i] <- as.character(a$Bottom[i])
    a$LoseSeed[i] <- a$Tseed[i]
    a$Loser[i] <- as.character(a$Top[i])
    a$ML[i] <- a$Bpct[i]/a$Tpct[i]*100
    a$Winpct[i] <- a$Bpct[i]
  }
}

first <- a[c(193:224),]
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%  ||  %4.0f", first$WinSeed,first$Winner,first$LoseSeed,first$Loser,first$Winpct*100,first$ML))
```


2nd round
```{r}
c <- read.csv("./Data-2nd-rd.csv", header = TRUE)

c$Top <- as.character(c$Top)
c$Bottom <- as.character(c$Bottom)
c$ML <- 0
c$WinSeed <- 0
c$Winner <- ""
c$LoseSeed <- 0
c$Loser <- ""
c$Winpct <- 0

for(i in seq(from=1, to=31, by=2)){
  if(first$result[i] > .5){
    #c$Top[((i+1)/2)+96] <- first$Top[i]
    c[((i+1)/2)+96,seq(from=4, to=50, by=2)] <- first[i,seq(from=4, to=50, by=2)]
  }
  if(first$result[i] < .5){
    c[((i+1)/2)+96,seq(from=4, to=50, by=2)] <- first[i,seq(from=5, to=51, by=2)]
  }
}
for(i in seq(from=2, to=32, by=2)){
  if(first$result[i] > .5){
    c[(i/2)+96,seq(from=5, to=51, by=2)] <- first[i,seq(from=4, to=50, by=2)]
  }
  if(first$result[i] < .5){
    c[(i/2)+96,seq(from=5, to=51, by=2)] <- first[i,seq(from=5, to=51, by=2)]
  }
}

cc <- c[c(1:96),]

w13 <- lm(Win~Tcon+Bcon+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o+Tken_n
          +Bken_n+Toff+Boff+Tsos+Bsos+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This
          +Bhis,data=cc)
c$result <- suppressWarnings(predict(w13, c))
sd2 <- sd(resid(w13))
c$Tpct <- pt((c$result-.5)/(sd2), nrow(c))
c$Bpct <-  pt(-(c$result-.5)/(sd2), nrow(c))
#winplot(c[c(1:96),])

for(i in c(1:112)){
  if(c$result[i] > .5){
    c$WinSeed[i] <- c$Tseed[i]
    c$Winner[i] <- as.character(c$Top[i])
    c$LoseSeed[i] <- c$Bseed[i]
    c$Loser[i] <- as.character(c$Bottom[i])
    c$ML[i] <- c$Tpct[i]/c$Bpct[i]*-100
    c$Winpct[i] <- c$Tpct[i]
  }
  if(c$result[i] < .5){
    c$WinSeed[i] <- c$Bseed[i]
    c$Winner[i] <- as.character(c$Bottom[i])
    c$LoseSeed[i] <- c$Tseed[i]
    c$Loser[i] <- as.character(c$Top[i])
    c$ML[i] <- c$Bpct[i]/c$Tpct[i]*100
    c$Winpct[i] <- c$Bpct[i]
  }
}

second <- c[c(97:112),]
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", second$WinSeed,second$Winner,second$LoseSeed,second$Loser,second$Winpct*100))
```


Sweet 16
```{r}
e <- read.csv("./Data-s16.csv", header = TRUE)
g <- read.csv("./Data-final.csv", header = TRUE)
h <- rbind(e,g)

e$Top <- as.character(e$Top)
e$Bottom <- as.character(e$Bottom)
e$ML <- 0
e$WinSeed <- 0
e$Winner <- ""
e$LoseSeed <- 0
e$Loser <- ""
e$Winpct <- 0

for(i in seq(from=1, to=15, by=2)){
  if(second$result[i] > .5){
    #c$Top[((i+1)/2)+96] <- first$Top[i]
    e[((i+1)/2)+48,seq(from=4, to=50, by=2)] <- second[i,seq(from=4, to=50, by=2)]
  }
  if(second$result[i] < .5){
    e[((i+1)/2)+48,seq(from=4, to=50, by=2)] <- second[i,seq(from=5, to=51, by=2)]
  }
}
for(i in seq(from=2, to=16, by=2)){
  if(second$result[i] > .5){
    e[(i/2)+48,seq(from=5, to=51, by=2)] <- second[i,seq(from=4, to=50, by=2)]
  }
  if(second$result[i] < .5){
    e[(i/2)+48,seq(from=5, to=51, by=2)] <- second[i,seq(from=5, to=51, by=2)]
  }
}

hh <- h[c(1:48,57:80,85:96,99:104),]

w41 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
          +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis,data=hh)
e$result <- suppressWarnings(predict(w41, e))
sd3 <- sd(resid(w41))
e$Tpct <- pt((e$result-.5)/(sd3), nrow(e))
e$Bpct <-  pt(-(e$result-.5)/(sd3), nrow(e))
#winplot(e[c(1:48),])

for(i in c(1:56)){
  if(e$result[i] > .5){
    e$WinSeed[i] <- e$Tseed[i]
    e$Winner[i] <- as.character(e$Top[i])
    e$LoseSeed[i] <- e$Bseed[i]
    e$Loser[i] <- as.character(e$Bottom[i])
    e$ML[i] <- e$Tpct[i]/e$Bpct[i]*-100
    e$Winpct[i] <- e$Tpct[i]
  }
  if(e$result[i] < .5){
    e$WinSeed[i] <- e$Bseed[i]
    e$Winner[i] <- as.character(e$Bottom[i])
    e$LoseSeed[i] <- e$Tseed[i]
    e$Loser[i] <- as.character(e$Top[i])
    e$ML[i] <- e$Bpct[i]/e$Tpct[i]*100
    e$Winpct[i] <- e$Bpct[i]
  }
}

s16 <- e[c(49:56),]
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", s16$WinSeed,s16$Winner,s16$LoseSeed,s16$Loser,s16$Winpct*100))
```


Elite 8
```{r}
g$Top <- as.character(g$Top)
g$Bottom <- as.character(g$Bottom)
g$ML <- 0
g$WinSeed <- 0
g$Winner <- ""
g$LoseSeed <- 0
g$Loser <- ""
g$Winpct <- 0

for(i in seq(from=1, to=7, by=2)){
  if(s16$result[i] > .5){
    #c$Top[((i+1)/2)+96] <- first$Top[i]
    g[((i+1)/2)+24,seq(from=4, to=50, by=2)] <- s16[i,seq(from=4, to=50, by=2)]
  }
  if(s16$result[i] < .5){
    g[((i+1)/2)+24,seq(from=4, to=50, by=2)] <- s16[i,seq(from=5, to=51, by=2)]
  }
}
for(i in seq(from=2, to=8, by=2)){
  if(s16$result[i] > .5){
    g[(i/2)+24,seq(from=5, to=51, by=2)] <- s16[i,seq(from=4, to=50, by=2)]
  }
  if(s16$result[i] < .5){
    g[(i/2)+24,seq(from=5, to=51, by=2)] <- s16[i,seq(from=5, to=51, by=2)]
  }
}

g$result <- suppressWarnings(predict(w41, g))
g$Tpct <- pt((g$result-.5)/(sd3), nrow(g))
g$Bpct <-  pt(-(g$result-.5)/(sd3), nrow(g))
#winplot(g[c(1:24,29:40,43:48),])

for(i in c(1:49)){
  if(g$result[i] > .5){
    g$WinSeed[i] <- g$Tseed[i]
    g$Winner[i] <- as.character(g$Top[i])
    g$LoseSeed[i] <- g$Bseed[i]
    g$Loser[i] <- as.character(g$Bottom[i])
    g$ML[i] <- g$Tpct[i]/g$Bpct[i]*-100
    g$Winpct[i] <- g$Tpct[i]
  }
  if(g$result[i] < .5){
    g$WinSeed[i] <- g$Bseed[i]
    g$Winner[i] <- as.character(g$Bottom[i])
    g$LoseSeed[i] <- g$Tseed[i]
    g$Loser[i] <- as.character(g$Top[i])
    g$ML[i] <- g$Bpct[i]/g$Tpct[i]*100
    g$Winpct[i] <- g$Bpct[i]
  }
}

e8 <- g[c(25:28),]
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", e8$WinSeed,e8$Winner,e8$LoseSeed,e8$Loser,e8$Winpct*100))
```


Final 4
```{r}
for(i in c(1,3)){
  if(e8$result[i] > .5){
    #c$Top[((i+1)/2)+96] <- first$Top[i]
    g[((i+1)/2)+40,seq(from=4, to=50, by=2)] <- e8[i,seq(from=4, to=50, by=2)]
  }
  if(e8$result[i] < .5){
    g[((i+1)/2)+40,seq(from=4, to=50, by=2)] <- e8[i,seq(from=5, to=51, by=2)]
  }
}
for(i in c(2,4)){
  if(e8$result[i] > .5){
    g[(i/2)+40,seq(from=5, to=51, by=2)] <- e8[i,seq(from=4, to=50, by=2)]
  }
  if(e8$result[i] < .5){
    g[(i/2)+40,seq(from=5, to=51, by=2)] <- e8[i,seq(from=5, to=51, by=2)]
  }
}

g$result <- suppressWarnings(predict(w41, g))
g$Tpct <- pt((g$result-.5)/(sd3), nrow(g))
g$Bpct <-  pt(-(g$result-.5)/(sd3), nrow(g))

for(i in c(1:49)){
  if(g$result[i] > .5){
    g$WinSeed[i] <- g$Tseed[i]
    g$Winner[i] <- as.character(g$Top[i])
    g$LoseSeed[i] <- g$Bseed[i]
    g$Loser[i] <- as.character(g$Bottom[i])
    g$ML[i] <- g$Tpct[i]/g$Bpct[i]*-100
    g$Winpct[i] <- g$Tpct[i]
  }
  if(g$result[i] < .5){
    g$WinSeed[i] <- g$Bseed[i]
    g$Winner[i] <- as.character(g$Bottom[i])
    g$LoseSeed[i] <- g$Tseed[i]
    g$Loser[i] <- as.character(g$Top[i])
    g$ML[i] <- g$Bpct[i]/g$Tpct[i]*100
    g$Winpct[i] <- g$Bpct[i]
  }
}

f4 <- g[c(41:42),]
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", f4$WinSeed,f4$Winner,f4$LoseSeed,f4$Loser,f4$Winpct*100))
```


Championship
```{r}
if(f4$result[1] > .5){
  #c$Top[((i+1)/2)+96] <- first$Top[i]
  g[49,seq(from=4, to=50, by=2)] <- f4[1,seq(from=4, to=50, by=2)]
}
if(f4$result[1] < .5){
  g[49,seq(from=4, to=50, by=2)] <- f4[1,seq(from=5, to=51, by=2)]
}
if(f4$result[2] > .5){
  g[49,seq(from=5, to=51, by=2)] <- f4[2,seq(from=4, to=50, by=2)]
}
if(f4$result[2] < .5){
  g[49,seq(from=5, to=51, by=2)] <- f4[2,seq(from=5, to=51, by=2)]
}

g$result <- suppressWarnings(predict(w41, g))
g$Tpct <- pt((g$result-.5)/(sd3), nrow(g))
g$Bpct <-  pt(-(g$result-.5)/(sd3), nrow(g))

for(i in c(1:49)){
  if(g$result[i] > .5){
    g$WinSeed[i] <- g$Tseed[i]
    g$Winner[i] <- as.character(g$Top[i])
    g$LoseSeed[i] <- g$Bseed[i]
    g$Loser[i] <- as.character(g$Bottom[i])
    g$ML[i] <- g$Tpct[i]/g$Bpct[i]*-100
    g$Winpct[i] <- g$Tpct[i]
  }
  if(g$result[i] < .5){
    g$WinSeed[i] <- g$Bseed[i]
    g$Winner[i] <- as.character(g$Bottom[i])
    g$LoseSeed[i] <- g$Tseed[i]
    g$Loser[i] <- as.character(g$Top[i])
    g$ML[i] <- g$Bpct[i]/g$Tpct[i]*100
    g$Winpct[i] <- g$Bpct[i]
  }
}

champ <- g[49,]
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", champ$WinSeed,champ$Winner,champ$LoseSeed,champ$Loser,champ$Winpct*100))
```


Results
```{r}
cat(sprintf("First Round"))
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%  ||  %4.0f", first$WinSeed,first$Winner,first$LoseSeed,first$Loser,first$Winpct*100,first$ML))

cat(sprintf("\n\nSecond Round"))
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", second$WinSeed,second$Winner,second$LoseSeed,second$Loser,second$Winpct*100))

cat(sprintf("\n\nSweet 16"))
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", s16$WinSeed,s16$Winner,s16$LoseSeed,s16$Loser,s16$Winpct*100))

cat(sprintf("\n\nElite 8"))
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", e8$WinSeed,e8$Winner,e8$LoseSeed,e8$Loser,e8$Winpct*100))

cat(sprintf("\n\nFinal 4"))
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", f4$WinSeed,f4$Winner,f4$LoseSeed,f4$Loser,f4$Winpct*100))

cat(sprintf("\n\nChampionship"))
cat(sprintf("\n#%2i %19s  ||   #%2i %19s  ||  %4.1f%%", champ$WinSeed,champ$Winner,champ$LoseSeed,champ$Loser,champ$Winpct*100))
```








