```{r}
library(leaps)
library(broom)
library(corrplot)
library(dplyr)
library(e1071)
library(rpart)
stand <- function(x){(x-min(x))/(max(x)-min(x))}
count <- 0
```

1st round
```{r}
aaa <- read.csv("./Data-1st-rd.csv", header = TRUE)

aaa$T1 <- as.numeric(aaa$Tseed == 1)
aaa$T2 <- as.numeric(aaa$Tseed == 2)
aaa$T3 <- as.numeric(aaa$Tseed == 3)
aaa$T4 <- as.numeric(aaa$Tseed == 4)
aaa$T5 <- as.numeric(aaa$Tseed == 5)
aaa$T6 <- as.numeric(aaa$Tseed == 6)
aaa$T7 <- as.numeric(aaa$Tseed == 7)
aaa$T8 <- as.numeric(aaa$Tseed == 8)

a <- aaa[c(1:192),]
```

```{r}
w1 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o
         +Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150
         +Bl150+Tstr+Bstr+This+Bhis+T1+T2+T3+T4+T5+T6+T7+T8,data=a)
summary(w1)
a$result <- predict(w1)
#36 -- 31 @60
####################################################################################################
w2 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
         +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis+T1
         +T2+T3+T4+T5+T6+T7+T8,data=a)
summary(w2)
a$result <- predict(w2)
#35 -- 32 @48-49,52,55
####################################################################################################
w3 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
         +Bdef+Tsos+Bsos+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+This+Bhis+T1+T2+T3+T4+T5+T6+T7
         +T8,data=a)
summary(w3)
a$result <- predict(w3)
#35 -- 30 @55
####################################################################################################
#
w4 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Toff+Boff+Tdef+Bdef+Tsos+Bsos
         +Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+This+Bhis+T1+T2+T3+T4+T5+T6+T7+T8,data=a)
summary(w4)
a$result <- predict(w4)
#32 -- 32 @49-51
#
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(1:192)){
  if(a$result[i] < j && a$Win[i] == 1){
    count = count + 1
  }
  if(a$result[i] > j && a$Win[i] == 0){
    count = count + 1
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
```

```{r}
l1 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o
          +Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150
          +Bl150+Tstr+Bstr+This+Bhis+T1+T2+T3+T4+T5+T6+T7+T8, data=a, family = "binomial")
a$result <- predict(l1, type = "response")
#33 -- 28 @46
####################################################################################################
l2 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o
          +Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150
          +Tstr+Bstr+This+Bhis+T1+T2+T3+T4+T5+T6+T7+T8, data=a, family = "binomial")
a$result <- predict(l2, type = "response")
#34 -- 27 @45
####################################################################################################
l3 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o
          +Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150
          +Bl150+This+Bhis+T1+T2+T3+T4+T5+T6+T7+T8, data=a, family = "binomial")
a$result <- predict(l3, type = "response")
#31 -- 29 @40-43,47
####################################################################################################
#
l4 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tken_o+Bken_o+Tken_n+Bken_n
          +Toff+Boff+Tdef+Bdef+Tsos+Bsos+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+This+Bhis+T1+T2
          +T3+T4+T5+T6+T7+T8, data=a, family = "binomial")
a$result <- predict(l4, type = "response")
#31 -- 27 @43-45
#
####################################################################################################
l5 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Toff+Boff+Tdef+Bdef+Tsos+Bsos+Tw50+Bw50+Tl50+Bl50
          +Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis+T1+T2+T3+T4+T5+T6+T7+T8, 
          data=a, family = "binomial")
a$result <- predict(l4, type = "response")
#32 -- 28 @45
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(1:192)){
  if(a$result[i] < j && a$Win[i] == 1){
    count = count + 1
    #y <- c(as.character(a$Top[i]), as.character(a$Bottom[i]))
    #print(y)
  }
  if(a$result[i] > j && a$Win[i] == 0){
    count = count + 1
    #y <- c(as.character(a$Top[i]), as.character(a$Bottom[i]))
    #print(y)
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
```

```{r}
fit <- rpart(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o
             +Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150
             +Tl150+Bl150+Tstr+Bstr+This+Bhis+T1+T2+T3+T4+T5+T6+T7+T8, method="class", data=a)

printcp(fit)
plotcp(fit)
summary(fit)

plot(fit, uniform=TRUE)
text(fit, use.n=TRUE, all=TRUE, cex=.8)
```
```{r}
filter(a, Bhis > 128.2665, Brpi > .5739) #13-0 for 0
# #5 - 2 / #6 - 5 / #7 - 3 / #8 - 3
filter(a, Bhis > 128.2665, Brpi < .5739) #4-3 for 1 #6 #7 #7
# #4 - 1 / #5 - 1 / #6 - 2 / #7 - 3
filter(a, Bhis < 128.2665, Brpi < .54845) #58-2 for 1  #1 #3
# #1 - 24 / #2 - 22 / #3 - 13 / #4 - 1
filter(a, Bhis < 128.2665, Brpi > .54845, Tken_n > 20.24) #31-4 for 1  #5 #6-2 #7
# #2 - 1 / #3 - 6 / #4 - 9 / #5 - 9 / #6 - 5 / #7 - 4 / #8 - 1
filter(a, Bhis < 128.2665, Brpi > .54845, Tken_n < 20.24, Tken_o < .7959, Bw50 < 3.5) #15-3 for 0 #6-3
# #4 - 3 / #5 - 2 / #6 - 6 / #7 - 2 / #8 - 5
filter(a, Bhis < 128.2665, Brpi > .54845, Tken_n < 20.24, Tken_o < .7959, Bw50 > 3.5) #6-3 for 1 #8-3
# #7 - 3 / #8 - 6
filter(a, Bhis < 128.2665, Brpi > .54845, Tken_n < 20.24, Tken_o > .7959, Bcon > .5031) #26-3 for 1 #6 #7 #8
# #3 - 2 / #4 - 1 / #5 - 3 / #6 - 5 / #7 - 9 / #8 - 9
filter(a, Bhis < 128.2665, Brpi > .54845, Tken_n < 20.24, Tken_o > .7959, Bcon < .5031, T4 < .5) #9-3 for0 #5-3
# #2 - 1 / #3 - 3 / #5 - 7 / #6 - 1
filter(a, Bhis < 128.2665, Brpi > .54845, Tken_n < 20.24, Tken_o > .7959, Bcon < .5031, T4 > .5) #8-1 for 1 #4
#4 - 9
```

2nd Round
```{r}
ccc <- read.csv("./Data-2nd-rd.csv", header = TRUE)
c <- ccc[c(1:96),]
```

```{r}
w11 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o
          +Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150
          +Bl150+Tstr+Bstr+This+Bhis,data=c)
summary(w11)
c$result <- predict(w11)
#15 -- 12 @46,57
####################################################################################################
w12 <- lm(Win~Tcon+Bcon+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o+Tken_n
          +Bken_n+Toff+Boff+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr
          +This+Bhis,data=c)
summary(w12)
c$result <- predict(w12)
#15 -- 12 @44,53-54
####################################################################################################
#
w13 <- lm(Win~Tcon+Bcon+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o+Bken_o+Tken_n
          +Bken_n+Toff+Boff+Tsos+Bsos+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This
          +Bhis,data=c)
summary(w13)
c$result <- predict(w13)
#14 -- 12 @46,52-54
#
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(1:96)){
  if(c$result[i] < j && c$Win[i] == 1){
    count = count + 1
  }
  if(c$result[i] > j && c$Win[i] == 0){
    count = count + 1
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
```

```{r}
l11 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
           +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, 
           data=c, family = "binomial")
c$result <- predict(l11, type = "response")
#17 -- 12 @33-35
####################################################################################################
l12 <- glm(Win~Tcon+Bcon+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef+Bdef+Tsos
           +Bsos+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, data=c, 
           family = "binomial")
c$result <- predict(l12, type = "response")
#13 -- 13 @50
####################################################################################################
l13 <- glm(Win~Tcon+Bcon+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+Tw50
           +Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+This+Bhis, data=c, family = "binomial")
c$result <- predict(l13, type = "response")
#13 -- 13 @40-43,49-53
####################################################################################################
#
l14 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef+Bdef+Tsos
           +Bsos+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+This+Bhis, data=c, family = "binomial")
c$result <- predict(l14, type = "response")
#13 -- 12 @46-49
#
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(1:96)){
  if(c$result[i] < j && c$Win[i] == 1){
    count = count + 1
    #y <- c(as.character(d$Top[i]), as.character(d$Bottom[i]))
    #print(y)
  }
  if(c$result[i] > j && c$Win[i] == 0){
    count = count + 1
    #y <- c(as.character(d$Top[i]), as.character(d$Bottom[i]))
    #print(y)
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
c$result <- format(c$result, scientific=F)
```

```{r}
fit2 <- rpart(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o
              +Bken_o+Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50
              +Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, method="class", data=c)

printcp(fit2)
plotcp(fit2)
summary(fit2)

plot(fit2, uniform=TRUE)
text(fit2, use.n=TRUE, all=TRUE, cex=.8)
```
```{r}
filter(c, Boff > 113.55, Tsos < .58135) #38-7 for 0 || 2v10, 2v7, 4v5, 3v11, 2v7, 2v7, 3v11
# 1v8 - 2 / 2v7 - 10 / 2v10 - 8 / 3v6 - 7 / 3v11 - 6 / 4v5 - 6 / 4v12 - 6
filter(c, Boff > 113.55, Tsos > .58135) #11-2 for 1 || 4v5, 1v9
# 1v8 - 2 / 1v9 - 3 / 2v7 - 2 / 3v6 - 1 / 3v11 - 2 / 4v5 - 2 / 5v13 - 1
filter(c, Boff < 113.55, Tsos < .5458) #7-2 for 0 || 2v7, 1v8
# 1v8 - 1 / 2v7 - 1 / 3v6 - 1 / 3v11 - 2 / 4v5 - 1 / 4v12 - 2 / 9v16 - 1
filter(c, Boff < 113.55, Tsos >= .5458) #28-1 for 1 || 1v8
# 1v8 - 7 / 1v9 - 8 / 2v7 - 2 / 3v11 - 1 / 4v5 - 3 / 5v13 - 2 / 6v14 - 2 / 10v15 - 1 / 11v14 - 2 / 12v13 - 1
```

Sweet 16
```{r}
eee <- read.csv("./Data-s16.csv", header = TRUE)
e <- eee[c(1:48),]
f <- rbind(c[,c(1:50)],e[,c(1:50)])
```

```{r}
w21 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
          +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis
          ,data=e)
summary(w21)
e$result <- predict(w21)
#0 -- 0 @49-56
####################################################################################################
w22 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
          +Bdef+Tsos+Bsos+T12+B12+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis,data=e)
summary(w22)
e$result <- predict(w22)
#0 -- 0 @48-56
####################################################################################################
#
w23 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef+Bdef+Tsos
          +Bsos+T12+B12+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis,data=e)
summary(w23)
e$result <- predict(w23)
#0 -- 0 @45-55
#
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(1:48)){
  if(e$result[i] < j && e$Win[i] == 1){
    count = count + 1
  }
  if(e$result[i] > j && e$Win[i] == 0){
    count = count + 1
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
```

```{r}
l21 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
           +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, 
           data=f, family = "binomial")
f$result <- predict(l21, type = "response")
#11 -- 9 @57
####################################################################################################
l22 <- glm(Win~Tcon+Bcon+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef+Bdef+Tsos
           +Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, data=f, 
           family = "binomial")
f$result <- predict(l22, type = "response")
#11 -- 9 @60-63
####################################################################################################
#
l23 <- glm(Win~Tcon+Bcon+Tloss+Bloss+Trpi+Brpi+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50
           +Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, data=f, family = "binomial")
f$result <- predict(l23, type = "response")
#11 -- 9 @55,63-65
#
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(97:144)){
  if(f$result[i] < j && f$Win[i] == 1){
    count = count + 1
  }
  if(f$result[i] > j && f$Win[i] == 0){
    count = count + 1
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
f$result <- format(f$result, scientific=F)
```

```{r}
fit3 <- rpart(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o
              +Bken_o+Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50
              +Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, method="class", data=e)

printcp(fit3)
plotcp(fit3)
summary(fit3)

plot(fit3, uniform=TRUE)
text(fit3, use.n=TRUE, all=TRUE, cex=.8)

fit4 <- rpart(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o
              +Bken_o+Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50
              +Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, method="class", data=f)

printcp(fit4)
plotcp(fit4)
summary(fit4)

plot(fit4, uniform=TRUE)
text(fit4, use.n=TRUE, all=TRUE, cex=.8)
```
```{r}
filter(e, Trpi > .6377) #36-7 for 1 #18-2
filter(e, Trpi < .6377, Bcon < .5211) #12-1 for 1 #3-0
filter(e, Trpi < .6377, Bcon > .5211, Bw50 > 10.5) #6-1 for 1 #0-0
filter(e, Trpi < .6377, Bcon > .5211, Bw50 < 10.5, Bstr < 7.5) #10-7 for 1 #5-2
filter(e, Trpi < .6377, Bcon > .5211, Bw50 < 10.5, Bstr > 7.5, Tsos < .5526) #22-0 for 0 #2-0
filter(e, Trpi < .6377, Bcon > .5211, Bw50 < 10.5, Bstr > 7.5, Tsos > .5526, Bsos > .5766) #14-2 for 0 #7-1
filter(e, Trpi < .6377, Bcon > .5211, Bw50 < 10.5, Bstr > 7.5, Tsos > .5526, Bsos < .5766, Twin < 22.5) #10-3 for 0 #3-0
filter(e, Trpi < .6377, Bcon > .5211, Bw50 < 10.5, Bstr > 7.5, Tsos > .5526, Bsos < .5766, Twin > 22.5) #9-4 for 1 #3-2

filter(e, Brpi > .62745) #11-4 for 0
filter(e, Brpi < .62745) #26-7 for 1
```


Final
```{r}
ggg <- read.csv("./Data-Final.csv", header = TRUE)
g <- ggg[c(1:24,29:40,43:48),]
h <- rbind(e[,c(1:50)],g[,c(1:50)])
k <- rbind(c[,c(1:50)],e[,c(1:50)],g[,c(1:50)])
```

```{r}
w31 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
          +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis,data=g)
summary(w31)
g$result <- predict(w31)
#0 -- 0 @42-51
####################################################################################################
w32 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
          +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tstr+Bstr+This+Bhis,data=g)
summary(w32)
g$result <- predict(w32)
#1 -- 0 @43-49
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(1:42)){
  if(g$result[i] < j && g$Win[i] == 1){
    count = count + 1
  }
  if(g$result[i] > j && g$Win[i] == 0){
    count = count + 1
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
```

```{r}
l31 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
           +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, 
           data=h, family = "binomial")
h$result <- predict(l31, type = "response")
#13 -- 9 @56-58 // S16 5 -- 5 @45-58 // final 8 -- 4 @56-58
####################################################################################################
l32 <- glm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
           +Bdef+Tsos+Bsos+T12+B12+Tl50+Bl50+Tl150+Bl150+Tstr+Bstr+This+Bhis, data=h, 
           family = "binomial")
h$result <- predict(l32, type = "response")
#13 -- 9 @57-58 // S16 6 -- 5 @a lot // final 7 -- 4 @57-58
####################################################################################################
#
l33 <- glm(Win~Tcon+Bcon+Twin+Bwin+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
           +Bdef+Tsos+Bsos+T12+B12+Tl50+Bl50+Tl150+Bl150+This+Bhis, data=h, family = "binomial")
h$result <- predict(l33, type = "response")
#11 -- 9 @60 // S16 5 -- 4 @52 // final 6 -- 4 @60-62
#
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(49:90)){
  if(h$result[i] < j && h$Win[i] == 1){
    count = count + 1
  }
  if(h$result[i] > j && h$Win[i] == 0){
    count = count + 1
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
h$result <- format(h$result, scientific=F)
```

```{r}
fit5 <- rpart(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o
              +Bken_o+Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50
              +Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, method="class", data=g)

printcp(fit5)
plotcp(fit5)
summary(fit5)

plot(fit5, uniform=TRUE)
text(fit5, use.n=TRUE, all=TRUE, cex=.8)

fit6 <- rpart(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Tken_o
              +Bken_o+Tken_n+Bken_n+Toff+Boff+Tdef+Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50
              +Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis, method="class", data=k)

printcp(fit6)
plotcp(fit6)
summary(fit6)

plot(fit6, uniform=TRUE)
text(fit6, use.n=TRUE, all=TRUE, cex=.8)
```
```{r}
filter(g, Brpi < 0.6067, Tw50 < 3.5) #7-3 for 0 // final 1-0 // S16 1-0 // 2nd 5-3
filter(g, Brpi < 0.6067, Tw50 > 3.5, Bdef < 92.3) #5-3 for 0 // final 1-1 // S16 1-1 // 2nd 3-1
filter(g, Brpi < 0.6067, Tw50 > 3.5, Bdef > 92.3) #39-3 for 1 // final 4-1 // S16 12-0 // 2nd 23-2
filter(g, Brpi > 0.6067, Toff > 120.85) #15-4 for 1 // final 7-3 // S16 7-1 // 2nd 1-0
filter(g, Brpi > 0.6067, Toff < 120.85, Tsos < .5767, Bsos > .5937) #5-4 for 1 // final 1-0 // S16 1-0 // 2nd 3-4
filter(g, Brpi > 0.6067, Toff < 120.85, Tsos < .5767, Bsos < .5937, Bhis > 61.4635) #41-5 for 0 // final 9-0 // S16 7-2 // 2nd 25-3
filter(g, Brpi > 0.6067, Toff < 120.85, Tsos < .5767, Bsos < .5937, Bhis < 61.4635) #5-4 for 1 // final 1-0 // S16 1-0 // 2nd 3-4
filter(g, Brpi > 0.6067, Toff < 120.85, Tsos > .5767, Bsos < .5637) #7-1 for 1 // final 0-0 // S16 3-0 // 2nd 4-1
filter(g, Brpi > 0.6067, Toff < 120.85, Tsos > .5767, Bsos > .5637, Bw50 < 7.5) #17-5 for 0 // final 6-1 // S16 7-3 // 2nd 4-2
filter(g, Brpi > 0.6067, Toff < 120.85, Tsos > .5767, Bsos > .5637, Bw50 > 7.5) #9-4 for 1 // final 3-3 // S16 0-1 // 2nd 6-0

filter(g, Toff < 115.95) #10-1 for 0
filter(g, Toff > 115.95, Bdef > 96.15) #8-1 for 1
filter(g, Toff > 115.95, Bdef < 96.15, Tdef < 92.65) #7-1 for 0
filter(g, Toff > 115.95, Bdef < 96.15, Tdef > 92.65) #8-6 for 1
```




Combo
```{r}
#
w41 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
          +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tw150+Bw150+Tl150+Bl150+Tstr+Bstr+This+Bhis,data=h)
summary(w41)
h$result <- predict(w41)
#12 -- 11 @49 // final 7 -- 6 @48-49 // S16 5 -- 5 @39-48,49-53
#
####################################################################################################
w42 <- lm(Win~Tcon+Bcon+Twin+Bwin+Tloss+Bloss+Trpi+Brpi+Tbpi_o+Bbpi_o+Tbpi_n+Bbpi_n+Toff+Boff+Tdef
          +Bdef+Tsos+Bsos+T12+B12+Tw50+Bw50+Tl50+Bl50+Tl150+Bl150+Tstr+Bstr+This+Bhis,data=h)
summary(w42)
h$result <- predict(w42)
#12 -- 12 @49-52 // final 7 -- 6 @49 // S16 5 -- 5 @40-45,50-52
####################################################################################################

for(j in seq(from=.3, to=.7, by=.01)){
for(i in c(1:90)){
  if(h$result[i] < j && h$Win[i] == 1){
    count = count + 1
  }
  if(h$result[i] > j && h$Win[i] == 0){
    count = count + 1
  }
}
  cat(sprintf("%5g %7i\n",j,count))
  count <- 0
}
```










